### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubschool/ole-ole-ole#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by RommelTJ** [comment]
Can I haz collaborator access?

**Comment by raghavendra98** [comment]
HI there..

**Comment by raghavendra98** [comment]
Adding a comment

**Comment by trprichard** [comment]
Please give me permission

**Comment by amyfan** [comment]
**Comment**

**Comment by amavuram** [comment]
Comment

**Comment by RommelTJ** [comment]
[Important notes](https://www.youtube.com/watch?v=dQw4w9WgXcQ).

**Comment by slander15** [comment]
comment.

**Comment by githubteacher** [comment]
😅

**Comment by githubteacher** [comment]
😐

**Comment by jonpilarski23** [comment]
wq'ut24y2457y6

**Comment by veenasingireddy** [comment]
ok, I just did.... Here u go.

**Comment by raghavendra98** [comment]
# Urgent
not really urgent...but want to see the title

**Comment by pkumar7usd** [comment]
Testing..

**Comment by jonpilarski23** [comment]
hello world

**Comment by davesey** [comment]
Yo

**Comment by lindapwu** [comment]
Yes, got it.

**Comment by githubteacher** [comment]
Comment!

**Comment by githubteacher** [comment]
@githubteacher Question?

**Comment by slander15** [comment]
@davesey question?

**Comment by davesey** [comment]
@slander15 response

**Comment by raghavendra98** [comment]
@RommelTJ  did you read my earlier comment?

**Comment by RommelTJ** [comment]
@raghavendra98 yep!

**Comment by abadwal** [comment]
Ole Ole Ole 🥇

**Comment by rahulsdsu** [comment]
comment
